### ISSUE TITLE
Endpoint to get token unknown

### ISSUE THREAD

**Issue by spdvi** [CIFP-Pau-Casesnoves-DAW/baleart-public-miriam-mohammed-joan#1]
No hi ha informació del endpoint per obtenir un token ni del format i credencials que s'han de passar.

**Comment by JoanUniverse** [comment]
Per a obtenir el token primer s'ha de crear un usuari. Després, a l'hora de fer el logit et retornarà el token que hauràs d'emprar per fer la resta de peticions. En poder posarem l'ajuda en condicions i ho explicarem millor!

**Comment by JoanUniverse** [comment]
El token s'ha de fer servir amb bearer authentication

**Comment by spdvi** [comment]
Ok, I managed to create a user and get a token:
![image](https://user-images.githubusercontent.com/62358226/153072772-58f01fbe-5098-4b78-bd0b-3b063a14dc26.png)

![image](https://user-images.githubusercontent.com/62358226/153072838-7c8ddc4f-ab94-4517-8b7d-e69ede415bf5.png)

And to the the list of Users:
![image](https://user-images.githubusercontent.com/62358226/153073251-9c49e259-a20b-4c25-8272-dbb4539359bf.png)

**Comment by JoanUniverse** [comment]
👍 👍
