### ISSUE TITLE
Endpoint para conseguir los comentarios que tiene un espacio

### ISSUE THREAD

**Issue by ZoePaganini** [CIFP-Pau-Casesnoves-DAW/baleart-public-miriam-mohammed-joan#10]
Buenas de nuevo, nos gustaría que hubiese un endpoint para poder conseguir todos los comentarios de un espacio, además, si pudiera ser posible, que en la información del comentario saliese el nombre del usuario en vez de su id.
Muchas gracias.

**Comment by miriamjimenezmolina24** [comment]
¡Buenas! Ya hemos implementado en la api vuestra sugerencia. 
Hemos añadido la siguiente ruta: /comentaris/espai/{idEspai}
Un ejemplo podría ser el siguiente: http://baleart.projectebaleart.com/public/api/comentaris/espai/1 
Si hubiese alguna duda la ruta también está añadida en la ayuda o directamente nos lo comentáis desde aquí, ¡un saludo!
