### ISSUE TITLE
Cose a millorar

### ISSUE THREAD

**Issue by tcampaner** [CIFP-Pau-Casesnoves-DAW/baleart-public-miriam-mohammed-joan#2]
Heu de millorar el format de l'ajuda, es mala de llegir (el millor es fer una taula)
Explicau al readme que el prier que han de fer es crear un usuar per després poder fer un login.
No he trobat a l'ajuda com fer un login.
Heu de contestar i tancar els issues.

**Comment by JoanUniverse** [comment]
Si Tomeu, ho tenim en compte. Tot d'una en poder ho posarem en ordre!

**Comment by JoanUniverse** [comment]
Llest 👍 !
