### ISSUE TITLE
GET obres throws 500 Internal Server Error

### ISSUE THREAD

**Issue by ZoePaganini** [CIFP-Pau-Casesnoves-DAW/baleart-public-miriam-mohammed-joan#3]
When you make the GET request to the indicated path, the response return the next error message:

<title>🧨 Target class [App\Http\Controllers\obraController] does not exist.</title>

![image](https://user-images.githubusercontent.com/77688974/153232394-7b6bfe02-8fe0-41eb-9c21-79a2429f4fe9.png)

**Comment by miriamjimenezmolina24** [comment]
Hem vist el motiu que causa aquest error i quan poguem ho corregirem. Vos avisarem quan estigui arreglat. Gràcies per avisar!

**Comment by miriamjimenezmolina24** [comment]
Tornau a provar-ho ara, en teoria hauria d'estar solucionat ^^
