### ISSUE TITLE
GET Request de Espais

### ISSUE THREAD

**Issue by ZoePaganini** [CIFP-Pau-Casesnoves-DAW/baleart-public-miriam-mohammed-joan#5]
En el endpoint de /espais, nos gustaría que saliese directamente la información del municipi, servicio y tipo. De lo contrario deberíamos hacer 4 requests para poder sacar toda la información de un espacio.
Además, tiene un parámetro llamado id_obra cuando en obra ya referencias a la exposición y de la exposición referencias a espacio, de la manera en la que está ahora mismo, da a entender de que un espacio solo puede tener una obra.
También, estaría bien que en la imagen saliera una URL de la imagen, en vez de un texto descrpitivo de ella.

![image](https://user-images.githubusercontent.com/77688974/154319936-83a587f9-b8f0-4d27-9259-0bb1b97c9c6d.png)

**Comment by ZoePaganini** [comment]
id_usuario se refiere al usuario gestor de ese espacio?

**Comment by miriamjimenezmolina24** [comment]
Hemos estado mirando vuestra sugerencia y ya la hemos implementado en local. En cuanto a id_obra parece que ha sido un error que no vimos anteriormente y lo corregiremos lo antes posible. ¡Gracias!

**Comment by miriamjimenezmolina24** [comment]
> id_usuario se refiere al usuario gestor de ese espacio?

Sí.

**Comment by miriamjimenezmolina24** [comment]
Ja hem realitzat els canvis, ja els podeu provar fent un GET de un espai.
