### ISSUE TITLE
Endpoint que devuelva las obras a partir del id de un autor

### ISSUE THREAD

**Issue by ZoePaganini** [CIFP-Pau-Casesnoves-DAW/baleart-public-miriam-mohammed-joan#6]
Nos gustaría que hubiese un endpoint el cual nos proporcionase todas las obras de un autor.
El endpoint se podría ser /obresbyautor/{id_autor}

**Comment by miriamjimenezmolina24** [comment]
Ya está implementado en la api. Para probarlo tenéis que usar la siguiente ruta: http://baleart.projectebaleart.com/public/api/autors/obres/idAutor
La ruta también está añadida en la ayuda, un saludo.
