### ISSUE TITLE
Endpoint que recoja los datos del usuario mediante el email.

### ISSUE THREAD

**Issue by Diego-bih** [CIFP-Pau-Casesnoves-DAW/baleart-public-miriam-mohammed-joan#8]
Seria posible obtener un endpoint del cual recoja los datos del usuario mediante el email. Lo necesitamos para poder visualizar la información del usuario en la aplicación ya que al hacer un login no obtenemos el id del usuario. Solo obtenemos el token.
Adjunto un toString() :

![image](https://user-images.githubusercontent.com/77398946/155354254-67994e51-dca8-47fa-af58-7bad5caa7288.png)

**Comment by ZoePaganini** [comment]
Buenas, también se podría hacer de otra manera. A la hora de hacer el login, además de status y result, se podría añadir el id del usuario al response? Para así poder pedir toda la información de nuestro usuario y no solo el token.
Muchas gracias.

**Comment by miriamjimenezmolina24** [comment]
¡Buenas! A la hora de hacer el login hemos añadido al response el id del usuario, a parte del status y el result. Un saludo.
