### ISSUE TITLE
Endpoint para recoger todas las valoraciones mediante el id de espacio

### ISSUE THREAD

**Issue by ZoePaganini** [CIFP-Pau-Casesnoves-DAW/baleart-public-miriam-mohammed-joan#9]
Buenas, 
si fuera posible, nos gustaría tener un endpoint para poder recoger todas las valoraciones de un espacio en concreto.

**Comment by miriamjimenezmolina24** [comment]
Buenas, ya hemos implementado el endpoint. Podéis probarlo en la siguiente ruta: 
http://baleart.projectebaleart.com/public/api/valoracions/espai/idEspai
La ruta está añadida en la página de ayuda por si hubiese alguna duda. 
Saludos ^^
